package com.example.wikispt.enums;

public enum TypeAction {
    SOUMISSION_ARTICLE,
    PUBLICATION_ARTICLE,
    REJET_ARTICLE,
    MODIFICATION_ARTICLE,
    SUPPRESSION_ARTICLE,
    CREATION_UTILISATEUR,
    DESACTIVATION_UTILISATEUR,
    REACTIVATION_UTILISATEUR,
    VERROUILLAGE_COMPTE,
    CREATION_CATEGORIE,
    SUPPRESSION_CATEGORIE
}